
export type Discourse = {
  number: number;
  title: string;
};

export const discourseList: Discourse[] = [
  { number: 1, title: "Connaissons-nous vraiment Dieu ?" },
  { number: 2, title: "Survivrez-vous aux derniers jours ?" },
  { number: 3, title: "Avançons au rythme de l’organisation unie de Jéhovah" },
  { number: 4, title: "Des preuves de l’existence de Dieu dans le monde qui nous entoure" },
  { number: 5, title: "Une aide réelle pour la famille" },
  { number: 6, title: "Le déluge et sa signification pour nous" },
  { number: 7, title: "Imitons « le Père des tendres miséricordes »" },
  { number: 8, title: "Vivons pour faire la volonté de Dieu, et non la nôtre" },
  { number: 9, title: "Soyons des auditeurs et des pratiquants de la Parole de Dieu" },
  { number: 10, title: "Soyons honnêtes en paroles et en actions" },
  { number: 11, title: "Comme Christ, ne faisons pas partie du monde" },
  { number: 12, title: "Notre conception de l’autorité compte aux yeux de Dieu" },
  { number: 13, title: "La pensée de Dieu sur le mariage et la sexualité" },
  { number: 14, title: "Un peuple pur qui honore Jéhovah" },
  { number: 15, title: "« Faisons du bien à tous »" },
  { number: 16, title: "Améliorons sans cesse nos relations avec Dieu" },
  { number: 17, title: "Utilisons tout ce que nous avons pour glorifier Dieu" },
  { number: 18, title: "Faites de Jéhovah votre forteresse" },
  { number: 19, title: "Comment connaître votre avenir ?" },
  { number: 20, title: "Le moment est-il venu pour Dieu de gouverner le monde ?" },
  { number: 21, title: "Accordez de la valeur à votre place dans le Royaume" },
  { number: 22, title: "Tirez-vous profit de ce que Jéhovah vous donne ?" },
  { number: 23, title: "La vie a bien un but" },
  { number: 24, title: "Avez-vous trouvé « une perle de grande valeur » ?" },
  { number: 25, title: "Luttons contre l’esprit du monde !" },
  { number: 26, title: "Comptez-vous aux yeux de Dieu ?" },
  { number: 27, title: "Comment prendre un bon départ dans le mariage" },
  { number: 28, title: "Manifestez du respect et de l’amour dans le mariage" },
  { number: 29, title: "Les responsabilités et les joies d’être parents" },
  { number: 30, title: "Comment améliorer la communication dans la famille" },
  { number: 31, title: "Êtes-vous conscients de vos besoins spirituels ?" },
  { number: 32, title: "Comment faire face aux inquiétudes de la vie" },
  { number: 33, title: "Connaîtrons-nous un jour la justice véritable ?" },
  { number: 34, title: "Recevrons-nous la marque pour la survie ?" },
  { number: 35, title: "La vie éternelle est-elle possible ? L’obtiendrez-vous ?" },
  { number: 36, title: "N’y a-t-il rien de mieux que cette vie ?" },
  { number: 37, title: "Les voies de Dieu sont-elles vraiment bénéfiques ?" },
  { number: 38, title: "Comment survivre à la fin du monde ?" },
  { number: 39, title: "Jésus Christ : sa victoire sur le monde. Comment et quand ?" },
  { number: 40, title: "Que nous réserve l’avenir proche ?" },
  { number: 41, title: "« Restez immobiles et voyez comment Jéhovah va agir pour vous sauver »" },
  { number: 42, title: "L’amour peut-il vaincre la haine ?" },
  { number: 43, title: "Les exigences de Dieu sont toujours pour notre bien" },
  { number: 44, title: "Comment les enseignements de Jésus peuvent-ils vous apporter des bienfaits ?" },
  { number: 45, title: "Suivons le chemin qui mène à la vie" },
  { number: 46, title: "Gardons une confiance ferme jusqu’à la fin" },
  { number: 47, title: "(Ne pas utiliser)" },
  { number: 48, title: "Restons fidèles face aux épreuves" },
  { number: 49, title: "Vivrons-nous un jour sur une terre purifiée ?" },
  { number: 50, title: "Comment prendre de bonnes décisions" },
  { number: 51, title: "La Bible transforme-t-elle votre vie ?" },
  { number: 52, title: "Qui est votre Dieu ?" },
  { number: 53, title: "Voyez-vous les choses comme Jéhovah ?" },
  { number: 54, title: "Bâtissez votre foi en Dieu et dans ses promesses" },
  { number: 55, title: "Comment se faire une bonne réputation aux yeux de Dieu ?" },
  { number: 56, title: "En quel dirigeant pouvez-vous avoir confiance ?" },
  { number: 57, title: "Comment endurer la persécution" },
  { number: 58, title: "Qui sont les vrais disciples de Christ ?" },
  { number: 59, title: "(Ne pas utiliser)" },
  { number: 60, title: "Quel est votre but dans la vie ?" },
  { number: 61, title: "En quelles promesses avez-vous confiance ?" },
  { number: 62, title: "Où pouvez-vous trouver le véritable espoir ?" },
  { number: 63, title: "Avez-vous l’esprit d’évangélisation ?" },
  { number: 64, title: "Voulez-vous être ‘ami des plaisirs’ ou ‘ami de Dieu’ ?" },
  { number: 65, title: "Favorisons la paix dans un monde en colère" },
  { number: 66, title: "Serez-vous un ouvrier pour la moisson ?" },
  { number: 67, title: "Méditons sur la Parole de Jéhovah et sur sa création" },
  { number: 68, title: "« Continuez à vous pardonner volontiers les uns aux autres »" },
  { number: 69, title: "Pourquoi manifester un amour plein d’abnégation ?" },
  { number: 70, title: "Pourquoi vous pouvez avoir confiance en Dieu" },
  { number: 71, title: "« Rester éveillé » : Pourquoi et comment" },
  { number: 72, title: "L’amour permet de reconnaître les vrais chrétiens" },
  { number: 73, title: "Acquérons « un cœur sage »" },
  { number: 74, title: "Les yeux de Jéhovah sont sur chacun de nous" },
  { number: 75, title: "Soutenez la souveraineté de Jéhovah dans votre vie" },
  { number: 76, title: "Quelle est l’utilité des principes de la Bible aujourd’hui ?" },
  { number: 77, title: "« Faisons toujours preuve d’hospitalité »" },
  { number: 78, title: "Servez Jéhovah d’un cœur joyeux" },
  { number: 79, title: "De qui voulez-vous être l’ami ?" },
  { number: 80, title: "Fondez-vous votre espérance sur la science ou sur la Bible ?" },
  { number: 81, title: "Qui est qualifié pour faire des disciples ?" },
  { number: 82, title: "(Ne pas utiliser)" },
  { number: 83, title: "Les chrétiens doivent-ils obéir aux Dix Commandements ?" },
  { number: 84, title: "Partagerons-nous le sort du monde ?" },
  { number: 85, title: "Une bonne nouvelle dans un monde de violence" },
  { number: 86, title: "Des prières que Dieu entend" },
  { number: 87, title: "Quelles relations entretenons-nous avec Dieu ?" },
  { number: 88, title: "Pourquoi vivre en accord avec les normes de la Bible ?" },
  { number: 89, title: "Venez, vous qui avez soif de vérité !" },
  { number: 90, title: "La vraie vie est à votre portée !" },
  { number: 91, title: "Le messie : sa présence et son règne" },
  { number: 92, title: "Le rôle de la religion dans les affaires du monde" },
  { number: 93, title: "Les catastrophes naturelles : Quand prendront-elles fin ?" },
  { number: 94, title: "La vraie religion comble les besoins de la société humaine" },
  { number: 95, title: "Ne nous laissons pas tromper par le spiritisme" },
  { number: 96, title: "Quel est l’avenir de la religion ?" },
  { number: 97, title: "Demeurons irréprochables au milieu d’une génération tortueuse" },
  { number: 98, title: "« La scène de ce monde est en train de changer »" },
  { number: 99, title: "Pourquoi faire confiance à la Bible" },
  { number: 100, title: "Comment nouer des amitiés solides et durables" },
  { number: 101, title: "Jéhovah : le « Grand Créateur »" },
  { number: 102, title: "Prêtons attention à « la parole prophétique »" },
  { number: 103, title: "Comment trouver la vraie joie ?" },
  { number: 104, title: "Parents, bâtissez-vous avec des matériaux à l’épreuve du feu ?" },
  { number: 105, title: "Trouvons la consolation dans toutes nos tribulations" },
  { number: 106, title: "Ceux qui ruinent la terre subiront le châtiment de Dieu" },
  { number: 107, title: "Récoltons les bienfaits d’une conscience bien éduquée" },
  { number: 108, title: "Vous pouvez regarder l’avenir avec optimisme !" },
  { number: 109, title: "Le Royaume de Dieu est proche" },
  { number: 110, title: "Une vie de famille heureuse : en accordant la première place à Dieu" },
  { number: 111, title: "La guérison complète de l’humanité : est-ce possible ?" },
  { number: 112, title: "(Ne pas utiliser)" },
  { number: 113, title: "Comment les jeunes peuvent-ils réussir leur vie et être heureux ?" },
  { number: 114, title: "Apprécions les merveilles de la création de Dieu" },
  { number: 115, title: "Comment se protéger des ruses de Satan" },
  { number: 116, title: "Faisons preuve de sagesse dans le choix de nos fréquentations" },
  { number: 117, title: "Comment vaincre le mal par le bien" },
  { number: 118, title: "Ayons la pensée de Jéhovah sur les jeunes" },
  { number: 119, title: "Les chrétiens se tiennent séparés du monde : pourquoi est-ce bénéfique ?" },
  { number: 120, title: "Pourquoi se soumettre dès maintenant à la domination de Dieu" },
  { number: 121, title: "Une communauté mondiale de frères sauvée du malheur" },
  { number: 122, title: "(Ne pas utiliser)" },
  { number: 123, title: "(Ne pas utiliser)" },
  { number: 124, title: "Raisons de croire que Dieu est l’auteur de la Bible" },
  { number: 125, title: "Pourquoi l’humanité a-t-elle besoin d’une rançon ?" },
  { number: 126, title: "Qui sera sauvé ?" },
  { number: 127, title: "Que se passe-t-il quand on meurt ?" },
  { number: 128, title: "L’enfer est-il réellement un lieu de flammes et de tourments ?" },
  { number: 129, title: "La Bible enseigne-t-elle la Trinité ?" },
  { number: 130, title: "La terre subsistera pour toujours" },
  { number: 131, title: "(Ne pas utiliser)" },
  { number: 132, title: "Bientôt la victoire sur la mort !" },
  { number: 133, title: "L’origine de l’homme : pourquoi vous y intéresser" },
  { number: 134, title: "Les chrétiens doivent-ils observer le sabbat ?" },
  { number: 135, title: "Le caractère sacré de la vie et du sang" },
  { number: 136, title: "Dieu approuve-t-il l’utilisation d’images dans le culte ?" },
  { number: 137, title: "Les miracles de la Bible ont-ils vraiment eu lieu ?" },
  { number: 138, title: "Vivons avec bon sens au sein d’un monde dépravé" },
  { number: 139, title: "La sagesse divine dans un monde épris de science" },
  { number: 140, title: "« Jésus Christ : qui est-il vraiment ? »" },
  { number: 141, title: "L’humanité gémit : jusqu’à quand ?" },
  { number: 142, title: "Pourquoi se réfugier en Jéhovah" },
  { number: 143, title: "Ayez confiance dans le Dieu de toute consolation" },
  { number: 144, title: "Une congrégation fidèle sous la direction de Christ" },
  { number: 145, title: "Qui est comme Jéhovah notre Dieu ?" },
  { number: 146, title: "Utilisons l’instruction pour louer Jéhovah" },
  { number: 147, title: "Ayons confiance dans le pouvoir de sauver de Jéhovah" },
  { number: 148, title: "Avez-vous la pensée de Dieu sur la vie ?" },
  { number: 149, title: "Marchez-vous avec Dieu ?" },
  { number: 150, title: "Le monde est-il condamné à disparaître ?" },
  { number: 151, title: "Jéhovah est « une hauteur sûre » pour son peuple" },
  { number: 152, title: "La bataille d’Harmaguédon : pourquoi et quand ?" },
  { number: 153, title: "Gardez constamment à l’esprit le « jour redoutable »" },
  { number: 154, title: "La domination humaine : l’heure du bilan" },
  { number: 155, title: "L’heure du jugement de Babylone est-elle arrivée ?" },
  { number: 156, title: "Le jour du jugement : un jour de terreur ou d’espoir ?" },
  { number: 157, title: "Les vrais chrétiens parent l’enseignement divin" },
  { number: 158, title: "Soyez courageux et mettez votre confiance en Jéhovah" },
  { number: 159, title: "Comment trouver la sécurité dans un monde dangereux" },
  { number: 160, title: "Préservez votre identité chrétienne !" },
  { number: 161, title: "Pourquoi Jésus a-t-il souffert ? Pourquoi est-il mort ?" },
  { number: 162, title: "Délivrés d’un monde de ténèbres" },
  { number: 163, title: "Pourquoi craindre le vrai Dieu ?" },
  { number: 164, title: "Dieu est-il toujours le souverain de la terre ?" },
  { number: 165, title: "À quelles valeurs êtes-vous attaché ?" },
  { number: 166, title: "La vraie foi : qu’est-ce que c’est, et comment la manifester ?" },
  { number: 167, title: "Agissons sagement dans un monde insensé" },
  { number: 168, title: "En sécurité dans un monde agité" },
  { number: 169, title: "Pourquoi se laisser guider par la Bible ?" },
  { number: 170, title: "Qui est qualifié pour diriger l’humanité ?" },
  { number: 171, title: "Vivez dans la paix dès à présent et pour l’éternité !" },
  { number: 172, title: "Quelle réputation avez-vous auprès de Dieu ?" },
  { number: 173, title: "Dieu approuve-t-il une religion en particulier ?" },
  { number: 174, title: "Le monde nouveau promis par Dieu : qui y sera admis ?" },
  { number: 175, title: "La Bible : un livre digne de foi" },
  { number: 176, title: "La paix et la sécurité véritables — Quand ?" },
  { number: 177, title: "Où trouver de l’aide dans les temps de détresse ?" },
  { number: 178, title: "Marchez dans la voie de l’intégrité" },
  { number: 179, title: "Rejetez les illusions du monde, poursuivez les réalités du Royaume" },
  { number: 180, title: "Pourquoi croire en la résurrection ?" },
  { number: 181, title: "Est-il plus tard que vous ne le pensez ?" },
  { number: 182, title: "Ce que le Royaume de Dieu fait pour nous dès maintenant" },
  { number: 183, title: "Détournons les yeux de ce qui ne vaut rien !" },
  { number: 184, title: "La mort est-elle la fin de tout ?" },
  { number: 185, title: "La vérité influence-t-elle votre vie ?" },
  { number: 186, title: "Unissez-vous au peuple heureux de Dieu" },
  { number: 187, title: "Pourquoi un Dieu d’amour permet-il la méchanceté ?" },
  { number: 188, title: "Placez-vous votre confiance en Jéhovah ?" },
  { number: 189, title: "Marcher avec Dieu procure des bienfaits, maintenant et pour toujours" },
  { number: 190, title: "La promesse d’un bonheur familial parfait" },
  { number: 191, title: "Comment l’amour et la foi peuvent vaincre le monde" },
  { number: 192, title: "Marchez-vous sur la route qui mène à la vie éternelle ?" },
  { number: 193, title: "Délivrés de la détresse" },
  { number: 194, title: "Les bienfaits de la sagesse qui vient de Dieu" },
];
